### ISSUE TITLE
extractSelectedText() behaviour differs between normal and minified JS

### ISSUE THREAD

**Issue by Pistos** [timdown/rangyinputs#14]
With the minified JS, if you put the cursor in a `<textarea>`, and don't select anything, then issue `$('textarea').extractSelectedText()` in the browser console, it deletes the character before the cursor, as if you pressed backspace.

The `-src.js` file doesn't behave this way.  The version of both files is allegedly 1.2.0.

**Comment by timdown** [comment]
I can't replicate this using the current source .js files in a slightly modified version of the demo page in Chrome or Firefox on my Mac. Which browser are you using?

**Comment by Pistos** [comment]
> Which browser are you using?

Chromium 43.0.2357.65 on Linux.  I will try to come up with a minimal example.  It's entirely possible that other code in our codebase was interfering.

**Comment by Pistos** [comment]
You're right, in a minimal example, the problem does not manifest.  It does appear in our code (I was able to reproduce it just now by swapping the minified and non-minified files), but I don't have time at the moment to try to more closely approximate the full situation (load all the other third-party libs, etc.).  You are welcome to create an account [here](http://maple.libertree.org/signup) to try to reproduce the problem yourself.  I couldn't quickly find how to replace a .js file loaded by a remote site, though.  One possibility is with an HTTP proxy.
