### ISSUE TITLE
Please specify License

### ISSUE THREAD

**Issue by shrumit** [timdown/rangyinputs#16]
@timdown
I would like to use your library in a project that I'm working on. Could you please add a License to the project?

**Comment by Flimm** [comment]
Yes please, a license would make this much more useful and clear. Here's a good website which will guide through the process in less than two minutes: choosealicense.com

**Comment by timdown** [comment]
Done. Sorry I haven't got round to this until now.

**Comment by Flimm** [comment]
Yay! Thank you.
