### ISSUE TITLE
Undo / redo support

### ISSUE THREAD

**Issue by ErisDS** [timdown/rangyinputs#6]
I'm using this lovely little library to try to replace CodeMirror in the [Ghost Editor](https://github.com/TryGhost/Ghost/pull/4373) with a plain textarea and I stumbled across the fact that making changes to a textarea with rangyinputs doesn't work with the browsers internal undo/redo.

I know that this is far from a simple problem to solve, and I'm also aware that you probably know far more about it than I do, seeing as researching the problem turned up [this](http://stackoverflow.com/questions/20124212/internet-explorer-alternative-to-document-execcommandinserttext-for-tex) :grin: 

As the answer to the question "can this be solved?" is "sort of", I was wondering if having support in rangyinputs would be welcomed either by default, or via an option?

**Comment by tiyse** [comment]
hımm
