### ISSUE TITLE
IE 9 Bug

### ISSUE THREAD

**Issue by guinness74** [timdown/rangyinputs#9]
I love this library and it works great in across all browsers, except I found an IE 9 bug in `surroundSelectedText()`. I am testing with IE 9.0.8112.16421 in Windows 7; the version shipped in the modern.ie Windows 7 IE 9 virtual machine.

If I have the following text in a <textarea> `let's wrap this text OK?` and I select `this text` from left-to-right with the mouse, I get `let's wrap <strong></strong>this text OK?` with the following function call.

    function stabButtonWrapSimple(event) {
        var tag = event.data.tag;

        // Drupal.settings.stab.textareaId is the id including # of the element.
        $(Drupal.settings.stab.textareaId).focus();

        // Wrap tag around selected text.
        $(Drupal.settings.stab.textareaId).surroundSelectedText("<" + tag + ">", "</" + tag + ">");    
    }

Is this something you would / could address? I am using this code in production and haven't been able to find a workaround.

**Comment by timdown** [comment]
I can't replicate this in my Windows 9 VM. Here's my demo page: http://jsfiddle.net/0ecm23vg/.

I'll need a bit more context to replicate the bug.

**Comment by guinness74** [comment]
I am using rangyinputs in a Drupal 7 module I wrote. As such, my jquery version is 1.4.4 because that's the version that shipped with Drupal 7. Perhaps that has something to do with it?

I looked at the [.focus()](http://api.jquery.com/focus/) documentation and it doesn't seem like anything has changed since 1.4.3.

I appreciate your time and help, what other information can I provide you with?

**Comment by timdown** [comment]
The version of jQuery is unlikely to make any difference: rangyinputs is only tacked onto jQuery because people like jQuery. It only uses jQuery to get hold of an element or list of elements.

If your module is in production, is there a live page I can see?

Otherwise, you could check `$(Drupal.settings.stab.textareaId).getSelection()` before calling surroundSelectedText to see whether the selection is as you expect at that point.

**Comment by guinness74** [comment]
It's in production, but behind a username and password.

`$(Drupal.settings.stab.textareaId).getSelection()` might be bugged.

I updated my code to:

    $(Drupal.settings.stab.textareaId).focus();

    var sel = $(Drupal.settings.stab.textareaId).getSelection();
    alert(sel.start + ", " + sel.end);

    $(Drupal.settings.stab.textareaId).surroundSelectedText("<" + tag + ">", "</" + tag + ">"); 

For this selection I got two different results.

![a](https://cloud.githubusercontent.com/assets/3831953/6287197/b9485ab8-b8dd-11e4-95bb-f82cba333743.png)

left-to-right mouse selection: 3, 3
right-to-left mouse selection: 8, 8

Does that help?

**Comment by timdown** [comment]
A little, in that it narrows down the potential location of the problem.

I've made pretty much the simplest possible demo, and it works fine in IE 9 in IETester and in IE 9 emulation in IE 11. Having a few problems with my IE 9 VM so currently downloading a new one. Does the following work for you?

http://jsfiddle.net/L8t4mssp/

**Comment by guinness74** [comment]
The demo link seems to work fine for me.

**Comment by timdown** [comment]
OK. I've tried putting IE 9 into quirks mode and that had no effect either, so I'm stumped without anything else to go on.

**Comment by guinness74** [comment]
I'm stumped too.

You previously mentioned the jQuery version wouldn't make a difference and jQuery does very little work, but did you try it with 1.4.4 to verify that claim?

Would emailing you my source code be a help?

**Comment by guinness74** [comment]
Fixed my issue. I was using jQuery's `.click()` to handle the click event on a `<div>`. I am using rangyinputs to drive some simple html buttons for a `<textarea>`. In IE 9, it seems like when you would click on the `<div>` to,say, bold some select text, the selection in the `<textarea>` would disappear... That's why start and end were equal. I got around this by using `<input type="button" />`.

**Comment by timdown** [comment]
I was going to suggest that as a potential cause but was confused by the fact that the selection start and end were being reported as non-zero values. I had thought that IE reverted them to zero when the selection was lost, but it turns out I was wrong about that.
